import { useState } from 'react';

interface Milestone {
  id: string;
  date: string;
  title: string;
  shortDesc: string;
  fullDesc: string;
}

const milestones: Milestone[] = [
  {
    id: '1990',
    date: 'October 1990',
    title: 'Project Launch',
    shortDesc: 'The Human Genome Project officially begins.',
    fullDesc: 'An international, collaborative research program is launched with the goal of completely mapping and understanding all the genes of human beings. The project was initially estimated to take 15 years and cost $3 billion.',
  },
  {
    id: '1996',
    date: 'February 1996',
    title: 'Bermuda Principles',
    shortDesc: 'Open data sharing established.',
    fullDesc: 'Scientists agree to the "Bermuda Principles," mandating that all human genomic sequence data generated by the project be made freely available in public databases within 24 hours of generation. This unprecedented open-science approach revolutionized biological research.',
  },
  {
    id: '2000',
    date: 'June 2000',
    title: 'Working Draft',
    shortDesc: 'First working draft announced.',
    fullDesc: 'A working draft of the human genome is jointly announced by the public HGP and the private company Celera Genomics. This draft covered about 90% of the genome, providing a crucial scaffold for future research.',
  },
  {
    id: '2003',
    date: 'April 2003',
    title: 'Project Completed',
    shortDesc: 'Final sequence published.',
    fullDesc: 'The Human Genome Project is declared complete, two years ahead of schedule. The final sequence achieved 99.99% accuracy and covered 99% of the gene-containing regions of the human genome, marking a monumental achievement in science.',
  },
];

export default function Timeline() {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <header className="text-center mb-16">
          <h1 className="text-biology-ink mb-4">The Human Genome Project</h1>
          <p className="text-lg text-biology-bark max-w-2xl mx-auto">
            A monumental international scientific research project that successfully mapped and sequenced the entire human genome, fundamentally changing medicine and biology.
          </p>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-20">
          <div className="bio-card p-6 text-center transform transition-transform hover:-translate-y-1">
            <div className="text-4xl font-display font-bold text-biology-dna mb-2">3.2B</div>
            <div className="text-sm font-semibold uppercase tracking-wider text-biology-bark">Base Pairs</div>
          </div>
          <div className="bio-card p-6 text-center transform transition-transform hover:-translate-y-1">
            <div className="text-4xl font-display font-bold text-biology-protein mb-2">~20k</div>
            <div className="text-sm font-semibold uppercase tracking-wider text-biology-bark">Genes</div>
          </div>
          <div className="bio-card p-6 text-center transform transition-transform hover:-translate-y-1">
            <div className="text-4xl font-display font-bold text-biology-membrane mb-2">$3B</div>
            <div className="text-sm font-semibold uppercase tracking-wider text-biology-bark">Investment</div>
          </div>
        </section>

        <section className="relative">
          <div className="absolute left-4 md:left-1/2 top-0 bottom-0 w-1 bg-biology-dna/30 transform md:-translate-x-1/2 rounded-full"></div>

          <div className="space-y-12">
            {milestones.map((milestone, index) => {
              const isExpanded = expandedId === milestone.id;
              const isEven = index % 2 === 0;

              return (
                <div key={milestone.id} className={`relative flex flex-col md:flex-row items-start ${isEven ? 'md:flex-row-reverse' : ''}`}>
                  
                  <div className="absolute left-4 md:left-1/2 w-4 h-4 rounded-full transform -translate-x-[6px] md:-translate-x-1/2 mt-6 z-10 transition-colors duration-300"
                       style={{ backgroundColor: isExpanded ? '#10B981' : '#3B82F6', boxShadow: isExpanded ? '0 0 0 4px rgba(16, 185, 129, 0.2)' : '0 0 0 4px rgba(59, 130, 246, 0.2)' }}>
                  </div>

                  <div className={`ml-12 md:ml-0 w-full md:w-[calc(50%-2rem)] ${isEven ? 'md:pl-8' : 'md:pr-8'}`}>
                    <button 
                      onClick={() => toggleExpand(milestone.id)}
                      className="w-full text-left focus:outline-none group"
                      aria-expanded={isExpanded}
                    >
                      <div className={`bio-card p-6 transition-all duration-300 ${isExpanded ? 'ring-2 ring-biology-protein border-transparent' : 'hover:border-biology-dna/50'}`}>
                        <div className="text-biology-dna font-semibold tracking-wide text-sm mb-1">{milestone.date}</div>
                        <h3 className="text-xl mb-2 group-hover:text-biology-dna transition-colors">{milestone.title}</h3>
                        <p className="text-biology-bark">{milestone.shortDesc}</p>
                        
                        <div className={`grid transition-all duration-300 ease-in-out ${isExpanded ? 'grid-rows-[1fr] opacity-100 mt-4' : 'grid-rows-[0fr] opacity-0'}`}>
                          <div className="overflow-hidden">
                            <div className="pt-4 border-t border-biology-clay/30 text-biology-ink/80 leading-relaxed">
                              {milestone.fullDesc}
                            </div>
                          </div>
                        </div>

                        <div className="mt-4 flex items-center text-xs font-medium text-biology-dna/70 uppercase tracking-wider">
                          {isExpanded ? (
                            <>
                              <span className="mr-1">Show less</span>
                              <svg className="w-4 h-4 transform rotate-180 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                              </svg>
                            </>
                          ) : (
                            <>
                              <span className="mr-1">Read more</span>
                              <svg className="w-4 h-4 transition-transform group-hover:translate-y-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                              </svg>
                            </>
                          )}
                        </div>
                      </div>
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      </div>
    </div>
  );
}
